service: idol-event-api

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-1
  stackTags:
    Name: ${self:custom.var.myname}
    Environment: ${self:custom.var.environment}
    SystemName: ${self:custom.var.mysystemname}
    ApplicationRole: api

functions:
  getEvents:
    name: ${self:custom.var.myname}
    handler: handler.lambda_handler
    role: arn:aws:iam::523736472015:role/service-role/api-get-event-role-xdyhloek
    timeout: 120
    memorySize: 1024
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: events
          method: get

plugins:
  - serverless-python-requirements
  - serverless-better-credentials

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true
  var:
    myname: ${self:custom.var.mysystemname}-${self:custom.var.environment}-${self:service}-api
    environment: ${opt:stage, 'dev'}
    mysystemname: ${file(./conf/settings.yml):SystemName}

package:
  patterns:
    - "!.vscode/**"
    - "!.git/**"
    - "!.gitignore"
    - "!.serverless"
    - "!.serverless/**"
    - "!README.md"
    - "!package*.json"
    - "!requirements.txt"
    - "!node_modules/**"
    - "!__pycache__"
    - "!yarn.lock"
    - "!conf/**"
