name: build and deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 build s3://${{ secrets.S3_BUCKET_NAME }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          AWS_REGION: "ap-northeast-1"
          PATHS: "/index.html"
